num1 = float(input("첫번째 숫자를 입력하세요: "))
num2 = float(input("두번째 숫자를 입력하세요: "))
print("덧셈 결과", num1 + num2)
print("뺄셈 결과", num1 - num2)
print("곱셈 결과", num1 * num2)
print("나눗셈 결과", num1 / num2)
print("\a")